// reactjs/src/App.jsx
import React, { Component } from "react";
import API from "./API";
import "./App.css";
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      title: "React.js Movie Search",
      keyword: "",
      loading: false,
      results: []
    };

    this.keywordChanged = this.keywordChanged.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
  }

  keywordChanged(e) {
    this.setState({
      keyword: e.target.value
    });
  }

  onSubmit(e) {
    e.preventDefault();
    this.setState({
      loading: true
    });
    API.search(this.state.keyword).then(results => {
      this.setState({
        results,
        loading: false
      });
    });
  }

  render() {
    const { title, keyword, loading, results } = this.state;

    return (
      <div>
        <h1> {title} </h1>
        <form onSubmit={this.onSubmit}>
          <label htmlFor="keyword">Keyword</label>
          <input
            value={keyword}
            className="u-full-width"
            type="text"
            id="keyword"
            name="keyword"
            onChange={this.keywordChanged}
          />
          <button type="submit">search</button>
        </form>
        {loading ? (
          <img src="https://i.imgur.com/LVHmLnb.gif" alt="Loading..." />
        ) : (
          ""
        )}
        <section className="results">
          {results.map(result => {
            return (
              <img
                key={result.id}
                src={`https://image.tmdb.org/t/p/w300_and_h450_bestv2/${
                  result.poster_path
                }`}
                alt={result.title}
              />
            );
          })}
        </section>
      </div>
    );
  }
}

export default App;

// vuejs/src/App.vue
<template>
  <div id="app">
    <h1>{{title}}</h1>
    <form @submit.prevent="formSubmitted()">
      <label for="keyword">Keyword</label>
      <input v-model="keyword" class="u-full-width" type="text" id="keyword" name="keyword">
      <button type="submit">search</button>
  </form>
  <img v-if="loading" src="./loader.gif" alt="" srcset="">
  <section class="results">
    <img :key="result.id" v-for="result in results" :src="'https://image.tmdb.org/t/p/w300_and_h450_bestv2/' + result.poster_path" alt="">
  </section>
  </div>
</template>

<script>
import API from "./API";

export default {
  name: "app",
  data() {
    return {
      title: "Vue Movie Search",
      keyword: "",
      results: [],
      loading: false
    };
  },
  methods: {
    formSubmitted() {
      this.results = [];
      this.loading = true;
      API.search(this.keyword).then(results => {
        this.results = results;
        this.loading = false;
      });
    }
  }
};
</script>

<style>
body {
  width: 80%;
  margin: 2em auto 0 auto;
}

.results {
  column-count: 3;
}

img {
  width: 100%;
}
</style>
